package deploy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/calvinchengx/synapse/internal/rules"
)

// CodexDeployer deploys rules as a single aggregated AGENTS.md to .codex/.
type CodexDeployer struct{}

func (d *CodexDeployer) Name() string { return "codex" }

// Deploy aggregates all rules into a single AGENTS.md file in
// <targetDir>/.codex/.
func (d *CodexDeployer) Deploy(ruleSet []rules.Rule, targetDir string) error {
	codexDir := filepath.Join(targetDir, ".codex")
	if err := os.MkdirAll(codexDir, 0755); err != nil {
		return fmt.Errorf("creating .codex: %w", err)
	}

	content := buildAgentsMD(ruleSet)
	dest := filepath.Join(codexDir, "AGENTS.md")
	if err := os.WriteFile(dest, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing AGENTS.md: %w", err)
	}

	return nil
}

// buildAgentsMD concatenates all rules into a single markdown document.
func buildAgentsMD(ruleSet []rules.Rule) string {
	var b strings.Builder

	b.WriteString("# Agent Instructions\n\n")
	b.WriteString("Generated by Synapse. Do not edit manually.\n\n")
	b.WriteString("---\n\n")

	for i, rule := range ruleSet {
		if i > 0 {
			b.WriteString("\n---\n\n")
		}

		// Section header
		b.WriteString(fmt.Sprintf("## %s", rule.Filename))
		if rule.Frontmatter.Description != "" {
			b.WriteString(fmt.Sprintf("\n\n> %s", rule.Frontmatter.Description))
		}
		b.WriteString("\n\n")
		b.WriteString(rule.Content)
		b.WriteString("\n")
	}

	return b.String()
}
